#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

// Actual FRLG trainers start here
#define TRAINER_NONE                               0
#define TRAINER_RIVAL_OAKS_LAB_SQUIRTLE            1
#define TRAINER_RIVAL_OAKS_LAB_BULBASAUR           2
#define TRAINER_RIVAL_OAKS_LAB_CHARMANDER          3
#define TRAINER_RIVAL_ROUTE22_EARLY_SQUIRTLE       4
#define TRAINER_RIVAL_ROUTE22_EARLY_BULBASAUR      5
#define TRAINER_RIVAL_ROUTE22_EARLY_CHARMANDER     6
#define TRAINER_LEADER_BROCK                       7
#define TRAINER_LEADER_BROCK_2                     8
#define TRAINER_LEADER_MISTY                       9
#define TRAINER_LEADER_MISTY_2                     10
#define TRAINER_LEADER_LT_SURGE                    11
#define TRAINER_LEADER_LT_SURGE_2                  12
#define TRAINER_LEADER_ERIKA                       13
#define TRAINER_LEADER_ERIKA_2                     14
#define TRAINER_LEADER_KOGA                        15
#define TRAINER_LEADER_KOGA_2                      16
#define TRAINER_LEADER_SABRINA                     17
#define TRAINER_LEADER_SABRINA_2                   18
#define TRAINER_LEADER_BLAINE                      19
#define TRAINER_LEADER_BLAINE_2                    20
#define TRAINER_LEADER_GIOVANNI                    21
#define TRAINER_LEADER_GIOVANNI_2                  22
#define TRAINER_LEADER_FALKNER                     23
#define TRAINER_LEADER_FALKNER_2                   24
#define TRAINER_LEADER_BUGSY                       25
#define TRAINER_LEADER_BUGSY_2                     26
#define TRAINER_LEADER_WHITNEY                     27
#define TRAINER_LEADER_WHITNEY_2                   28
#define TRAINER_LEADER_MORTY                       29
#define TRAINER_LEADER_MORTY_2                     30
#define TRAINER_LEADER_CHUCK                       31
#define TRAINER_LEADER_CHUCK_2                     32
#define TRAINER_LEADER_JASMINE                     33
#define TRAINER_LEADER_JASMINE_2                   34
#define TRAINER_LEADER_PRYCE                       35
#define TRAINER_LEADER_PRYCE_2                     36
#define TRAINER_LEADER_CLAIR                       37
#define TRAINER_LEADER_CLAIR_2                     38
#define TRAINER_BUG_CATCHER_RICK                   39
#define TRAINER_BUG_CATCHER_DOUG                   40
#define TRAINER_BUG_CATCHER_ANTHONY                41
#define TRAINER_BUG_CATCHER_CHARLIE                42
#define TRAINER_BUG_CATCHER_SAMMY                  43
#define TRAINER_CAMPER_LIAM                        44
#define TRAINER_LASS_JANICE                        45
#define TRAINER_LASS_JANICE_2                      46
#define TRAINER_LASS_JANICE_3                      47
#define TRAINER_BUG_CATCHER_COLTON                 48
#define TRAINER_BUG_CATCHER_COLTON_2               49
#define TRAINER_BUG_CATCHER_COLTON_3               50
#define TRAINER_YOUNGSTER_BEN                      51
#define TRAINER_YOUNGSTER_BEN_2                    52
#define TRAINER_YOUNGSTER_BEN_3                    53
#define TRAINER_BUG_CATCHER_GREG                   54
#define TRAINER_BUG_CATCHER_GREG_2                 55
#define TRAINER_BUG_CATCHER_GREG_3                 56
#define TRAINER_YOUNGSTER_CALVIN                   57
#define TRAINER_YOUNGSTER_CALVIN_2                 58
#define TRAINER_YOUNGSTER_CALVIN_3                 59
#define TRAINER_LASS_SALLY                         60
#define TRAINER_LASS_SALLY_2                       61
#define TRAINER_LASS_SALLY_3                       62
#define TRAINER_BUG_CATCHER_JAMES                  63
#define TRAINER_BUG_CATCHER_JAMES_2                64
#define TRAINER_BUG_CATCHER_JAMES_3                65
#define TRAINER_LASS_ROBIN                         66
#define TRAINER_LASS_ROBIN_2                       67
#define TRAINER_LASS_ROBIN_3                       68
#define TRAINER_BUG_CATCHER_KENT                   69
#define TRAINER_LASS_IRIS                          70
#define TRAINER_SUPER_NERD_JOVAN                   71
#define TRAINER_BUG_CATCHER_ROBBY                  72
#define TRAINER_LASS_MIRIAM                        73
#define TRAINER_YOUNGSTER_JOSH                     74
#define TRAINER_HIKER_MARCOS                       75
#define TRAINER_TEAM_ROCKET_GRUNT                  76
#define TRAINER_TEAM_ROCKET_GRUNT_2                77
#define TRAINER_TEAM_ROCKET_GRUNT_3                78
#define TRAINER_TEAM_ROCKET_GRUNT_4                79
#define TRAINER_SUPER_NERD_MIGUEL                  80
#define TRAINER_LASS_CRISSY                        81
#define TRAINER_LASS_CRISSY_2                      82
#define TRAINER_LASS_CRISSY_3                      83
#define TRAINER_SWIMMER_MALE_LUIS                  84
#define TRAINER_PICNICKER_DIANA                    85
#define TRAINER_RIVAL_CERULEAN_SQUIRTLE            86
#define TRAINER_RIVAL_CERULEAN_BULBASAUR           87
#define TRAINER_RIVAL_CERULEAN_CHARMANDER          88
#define TRAINER_TEAM_ROCKET_GRUNT_5                89
#define TRAINER_BUG_CATCHER_CALE                   90
#define TRAINER_BUG_CATCHER_CALE_2                 91
#define TRAINER_BUG_CATCHER_CALE_3                 92
#define TRAINER_LASS_ALI                           93
#define TRAINER_LASS_ALI_2                         94
#define TRAINER_LASS_ALI_3                         95
#define TRAINER_YOUNGSTER_TIMMY                    96
#define TRAINER_YOUNGSTER_TIMMY_2                  97
#define TRAINER_YOUNGSTER_TIMMY_3                  98
#define TRAINER_LASS_RELI                          99
#define TRAINER_LASS_RELI_2                        100
#define TRAINER_LASS_RELI_3                        101
#define TRAINER_CAMPER_ETHAN                       102
#define TRAINER_CAMPER_ETHAN_2                     103
#define TRAINER_CAMPER_ETHAN_3                     104
#define TRAINER_TEAM_ROCKET_GRUNT_6                105
#define TRAINER_CAMPER_SHANE                       106
#define TRAINER_CAMPER_SHANE_2                     107
#define TRAINER_CAMPER_SHANE_3                     108
#define TRAINER_HIKER_FRANKLIN                     109
#define TRAINER_HIKER_FRANKLIN_2                   110
#define TRAINER_HIKER_FRANKLIN_3                   111
#define TRAINER_HIKER_WAYNE                        112
#define TRAINER_HIKER_WAYNE_2                      113
#define TRAINER_HIKER_WAYNE_3                      114
#define TRAINER_YOUNGSTER_JOEY                     115
#define TRAINER_YOUNGSTER_JOEY_2                   116
#define TRAINER_YOUNGSTER_JOEY_3                   117
#define TRAINER_YOUNGSTER_DAN                      118
#define TRAINER_YOUNGSTER_DAN_2                    119
#define TRAINER_YOUNGSTER_DAN_3                    120
#define TRAINER_PICNICKER_KELSEY                   121
#define TRAINER_PICNICKER_KELSEY_2                 122
#define TRAINER_PICNICKER_KELSEY_3                 123
#define TRAINER_HIKER_NOB                          124
#define TRAINER_HIKER_NOB_2                        125
#define TRAINER_HIKER_NOB_3                        126
#define TRAINER_CAMPER_FLINT                       127
#define TRAINER_CAMPER_FLINT_2                     128
#define TRAINER_CAMPER_FLINT_3                     129
#define TRAINER_YOUNGSTER_CHAD                     130
#define TRAINER_YOUNGSTER_CHAD_2                   131
#define TRAINER_YOUNGSTER_CHAD_3                   132
#define TRAINER_LASS_HALEY                         133
#define TRAINER_LASS_HALEY_2                       134
#define TRAINER_LASS_HALEY_3                       135
#define TRAINER_BUG_CATCHER_KEIGO                  136
#define TRAINER_BUG_CATCHER_KEIGO_2                137
#define TRAINER_BUG_CATCHER_KEIGO_3                138
#define TRAINER_CAMPER_RICKY                       139
#define TRAINER_CAMPER_RICKY_2                     140
#define TRAINER_CAMPER_RICKY_3                     141
#define TRAINER_PICNICKER_NANCY                    142
#define TRAINER_PICNICKER_NANCY_2                  143
#define TRAINER_PICNICKER_NANCY_3                  144
#define TRAINER_BUG_CATCHER_ELIJAH                 145
#define TRAINER_BUG_CATCHER_ELIJAH_2               146
#define TRAINER_BUG_CATCHER_ELIJAH_3               147
#define TRAINER_PICNICKER_ISABELLE                 148
#define TRAINER_PICNICKER_ISABELLE_2               149
#define TRAINER_PICNICKER_ISABELLE_3               150
#define TRAINER_CAMPER_JEFF                        151
#define TRAINER_CAMPER_JEFF_2                      152
#define TRAINER_CAMPER_JEFF_3                      153
#define TRAINER_YOUNGSTER_EDDIE                    154
#define TRAINER_YOUNGSTER_EDDIE_2                  155
#define TRAINER_YOUNGSTER_EDDIE_3                  156
#define TRAINER_GAMER_HUGO                         157
#define TRAINER_GAMER_HUGO_2                       158
#define TRAINER_GAMER_HUGO_3                       159
#define TRAINER_YOUNGSTER_DAVE                     160
#define TRAINER_YOUNGSTER_DAVE_2                   161
#define TRAINER_YOUNGSTER_DAVE_3                   162
#define TRAINER_YOUNGSTER_DILLON                   163
#define TRAINER_YOUNGSTER_DILLON_2                 164
#define TRAINER_YOUNGSTER_DILLON_3                 165
#define TRAINER_ENGINEER_BERNIE                    166
#define TRAINER_ENGINEER_BERNIE_2                  167
#define TRAINER_ENGINEER_BERNIE_3                  168
#define TRAINER_GAMER_JASPER                       169
#define TRAINER_GAMER_JASPER_2                     170
#define TRAINER_GAMER_JASPER_3                     171
#define TRAINER_ENGINEER_BRAXTON                   172
#define TRAINER_ENGINEER_BRAXTON_2                 173
#define TRAINER_ENGINEER_BRAXTON_3                 174
#define TRAINER_GAMER_DARIAN                       175
#define TRAINER_GAMER_DARIAN_2                     176
#define TRAINER_GAMER_DARIAN_3                     177
#define TRAINER_YOUNGSTER_YASU                     178
#define TRAINER_YOUNGSTER_YASU_2                   179
#define TRAINER_YOUNGSTER_YASU_3                   180
#define TRAINER_GAMER_DIRK                         181
#define TRAINER_GAMER_DIRK_2                       182
#define TRAINER_GAMER_DIRK_3                       183
#define TRAINER_GENTLEMAN_THOMAS                   184
#define TRAINER_GENTLEMAN_ARTHUR                   185
#define TRAINER_YOUNGSTER_TYLER                    186
#define TRAINER_LASS_ANN                           187
#define TRAINER_SAILOR_LEONARD                     188
#define TRAINER_SAILOR_DUNCAN                      189
#define TRAINER_SAILOR_DYLAN                       190
#define TRAINER_SAILOR_HUEY                        191
#define TRAINER_FISHERMAN_BARNY                    192
#define TRAINER_SAILOR_PHILLIP                     193
#define TRAINER_SAILOR_TREVOR                      194
#define TRAINER_SAILOR_EDMOND                      195
#define TRAINER_FISHERMAN_DALE                     196
#define TRAINER_GENTLEMAN_BROOKS                   197
#define TRAINER_GENTLEMAN_LAMAR                    198
#define TRAINER_LASS_DAWN                          199
#define TRAINER_RIVAL_SS_ANNE_SQUIRTLE             200
#define TRAINER_RIVAL_SS_ANNE_BULBASAUR            201
#define TRAINER_RIVAL_SS_ANNE_CHARMANDER           202
#define TRAINER_SAILOR_DWAYNE                      203
#define TRAINER_ENGINEER_BAILY                     204
#define TRAINER_GENTLEMAN_TUCKER                   205
#define TRAINER_PICNICKER_ALICIA                   206
#define TRAINER_PICNICKER_ALICIA_2                 207
#define TRAINER_PICNICKER_ALICIA_3                 208
#define TRAINER_HIKER_JEREMY                       209
#define TRAINER_HIKER_JEREMY_2                     210
#define TRAINER_HIKER_JEREMY_3                     211
#define TRAINER_CAMPER_CHRIS                       212
#define TRAINER_CAMPER_CHRIS_2                     213
#define TRAINER_CAMPER_CHRIS_3                     214
#define TRAINER_BUG_CATCHER_BRENT                  215
#define TRAINER_BUG_CATCHER_BRENT_2                216
#define TRAINER_BUG_CATCHER_BRENT_3                217
#define TRAINER_BUG_CATCHER_CONNER                 218
#define TRAINER_BUG_CATCHER_CONNER_2               219
#define TRAINER_BUG_CATCHER_CONNER_3               220
#define TRAINER_CAMPER_DREW                        221
#define TRAINER_CAMPER_DREW_2                      222
#define TRAINER_CAMPER_DREW_3                      223
#define TRAINER_HIKER_BRICE                        224
#define TRAINER_HIKER_BRICE_2                      225
#define TRAINER_HIKER_BRICE_3                      226
#define TRAINER_PICNICKER_CAITLIN                  227
#define TRAINER_PICNICKER_CAITLIN_2                228
#define TRAINER_PICNICKER_CAITLIN_3                229
#define TRAINER_HIKER_ALAN                         230
#define TRAINER_HIKER_ALAN_2                       231
#define TRAINER_HIKER_ALAN_3                       232
#define TRAINER_PICNICKER_HEIDI                    233
#define TRAINER_PICNICKER_HEIDI_2                  234
#define TRAINER_PICNICKER_HEIDI_3                  235
#define TRAINER_POKEMANIAC_MARK                    236
#define TRAINER_POKEMANIAC_MARK_2                  237
#define TRAINER_POKEMANIAC_MARK_3                  238
#define TRAINER_POKEMANIAC_ASHTON                  239
#define TRAINER_POKEMANIAC_WINSTON                 240
#define TRAINER_PICNICKER_MARTHA                   241
#define TRAINER_POKEMANIAC_STEVE                   242
#define TRAINER_HIKER_ALLEN                        243
#define TRAINER_HIKER_ERIC                         244
#define TRAINER_HIKER_LENNY                        245
#define TRAINER_HIKER_OLIVER                       246
#define TRAINER_HIKER_LUCAS                        247
#define TRAINER_PICNICKER_SOFIA                    248
#define TRAINER_HIKER_DUDLEY                       249
#define TRAINER_POKEMANIAC_COOPER                  250
#define TRAINER_PICNICKER_LEAH                     251
#define TRAINER_PICNICKER_ARIANA                   252
#define TRAINER_PICNICKER_DANA                     253
#define TRAINER_PICNICKER_CAROL                    254
#define TRAINER_PICNICKER_CAROL_2                  255
#define TRAINER_PICNICKER_CAROL_3                  256
#define TRAINER_HIKER_CLARK                        257
#define TRAINER_HIKER_CLARK_2                      258
#define TRAINER_HIKER_CLARK_3                      259
#define TRAINER_HIKER_TRENT                        260
#define TRAINER_HIKER_TRENT_2                      261
#define TRAINER_HIKER_TRENT_3                      262
#define TRAINER_POKEMANIAC_HERMAN                  263
#define TRAINER_POKEMANIAC_HERMAN_2                264
#define TRAINER_POKEMANIAC_HERMAN_3                265
#define TRAINER_RIVAL_POKEMON_TOWER_SQUIRTLE       266
#define TRAINER_RIVAL_POKEMON_TOWER_BULBASAUR      267
#define TRAINER_RIVAL_POKEMON_TOWER_CHARMANDER     268
#define TRAINER_CHANNELER_HOPE                     269
#define TRAINER_CHANNELER_PATRICIA                 270
#define TRAINER_CHANNELER_CARLY                    271
#define TRAINER_CHANNELER_LAUREL                   272
#define TRAINER_CHANNELER_JODY                     273
#define TRAINER_CHANNELER_PAULA                    274
#define TRAINER_CHANNELER_RUTH                     275
#define TRAINER_CHANNELER_TAMMY                    276
#define TRAINER_CHANNELER_KARINA                   277
#define TRAINER_CHANNELER_JANAE                    278
#define TRAINER_CHANNELER_ANGELICA                 279
#define TRAINER_CHANNELER_JENNIFER                 280
#define TRAINER_CHANNELER_EMILIA                   281
#define TRAINER_LASS_JULIA                         282
#define TRAINER_LASS_JULIA_2                       283
#define TRAINER_LASS_JULIA_3                       284
#define TRAINER_GAMER_RICH                         285
#define TRAINER_GAMER_RICH_2                       286
#define TRAINER_GAMER_RICH_3                       287
#define TRAINER_SUPER_NERD_GLENN                   288
#define TRAINER_SUPER_NERD_GLENN_2                 289
#define TRAINER_SUPER_NERD_GLENN_3                 290
#define TRAINER_TWINS_ELI_ANNE                     291
#define TRAINER_TWINS_ELI_ANNE_2                   292
#define TRAINER_TWINS_ELI_ANNE_3                   293
#define TRAINER_LASS_PAIGE                         294
#define TRAINER_LASS_PAIGE_2                       295
#define TRAINER_LASS_PAIGE_3                       296
#define TRAINER_SUPER_NERD_LESLIE                  297
#define TRAINER_SUPER_NERD_LESLIE_2                298
#define TRAINER_SUPER_NERD_LESLIE_3                299
#define TRAINER_LASS_ANDREA                        300
#define TRAINER_LASS_ANDREA_2                      301
#define TRAINER_LASS_ANDREA_3                      302
#define TRAINER_LASS_MEGAN                         303
#define TRAINER_LASS_MEGAN_2                       304
#define TRAINER_LASS_MEGAN_3                       305
#define TRAINER_BIKER_JAREN                        306
#define TRAINER_BIKER_JAREN_2                      307
#define TRAINER_BIKER_JAREN_3                      308
#define TRAINER_BIKER_RICARDO                      309
#define TRAINER_BIKER_RICARDO_2                    310
#define TRAINER_BIKER_RICARDO_3                    311
#define TRAINER_GAMER_STAN                         312
#define TRAINER_GAMER_STAN_2                       313
#define TRAINER_GAMER_STAN_3                       314
#define TRAINER_SUPER_NERD_AIDAN                   315
#define TRAINER_SUPER_NERD_AIDAN_2                 316
#define TRAINER_SUPER_NERD_AIDAN_3                 317
#define TRAINER_LASS_KAY                           318
#define TRAINER_BEAUTY_BRIDGET                     319
#define TRAINER_COOLTRAINER_MARY                   320
#define TRAINER_LASS_LISA                          321
#define TRAINER_PICNICKER_TINA                     322
#define TRAINER_BEAUTY_LORI                        323
#define TRAINER_BEAUTY_TAMIA                       324
#define TRAINER_YOUNG_COUPLE_LEA_JED               325
#define TRAINER_YOUNG_COUPLE_LEA_JED_2             326
#define TRAINER_YOUNG_COUPLE_LEA_JED_3             327
#define TRAINER_TEAM_ROCKET_GRUNT_7                328
#define TRAINER_TEAM_ROCKET_GRUNT_8                329
#define TRAINER_TEAM_ROCKET_GRUNT_9                330
#define TRAINER_TEAM_ROCKET_GRUNT_10               331
#define TRAINER_TEAM_ROCKET_GRUNT_11               332
#define TRAINER_TEAM_ROCKET_GRUNT_12               333
#define TRAINER_TEAM_ROCKET_GRUNT_13               334
#define TRAINER_TEAM_ROCKET_GRUNT_14               335
#define TRAINER_TEAM_ROCKET_GRUNT_15               336
#define TRAINER_TEAM_ROCKET_GRUNT_16               337
#define TRAINER_TEAM_ROCKET_GRUNT_17               338
#define TRAINER_TEAM_ROCKET_GRUNT_18               339
#define TRAINER_BOSS_GIOVANNI                      340
#define TRAINER_TEAM_ROCKET_GRUNT_19               341
#define TRAINER_TEAM_ROCKET_GRUNT_20               342
#define TRAINER_TEAM_ROCKET_GRUNT_21               343
#define TRAINER_FISHERMAN_NED                      344
#define TRAINER_FISHERMAN_NED_2                    345
#define TRAINER_FISHERMAN_NED_3                    346
#define TRAINER_FISHERMAN_CHIP                     347
#define TRAINER_FISHERMAN_CHIP_2                   348
#define TRAINER_FISHERMAN_CHIP_3                   349
#define TRAINER_FISHERMAN_HANK                     350
#define TRAINER_FISHERMAN_HANK_2                   351
#define TRAINER_FISHERMAN_HANK_3                   352
#define TRAINER_FISHERMAN_ELLIOT                   353
#define TRAINER_FISHERMAN_ELLIOT_2                 354
#define TRAINER_FISHERMAN_ELLIOT_3                 355
#define TRAINER_YOUNG_COUPLE_GIA_JES               356
#define TRAINER_YOUNG_COUPLE_GIA_JES_2             357
#define TRAINER_YOUNG_COUPLE_GIA_JES_3             358
#define TRAINER_ROCKER_LUCA                        359
#define TRAINER_ROCKER_LUCA_2                      360
#define TRAINER_ROCKER_LUCA_3                      361
#define TRAINER_CAMPER_JUSTIN                      362
#define TRAINER_CAMPER_JUSTIN_2                    363
#define TRAINER_CAMPER_JUSTIN_3                    364
#define TRAINER_FISHERMAN_ANDREW                   365
#define TRAINER_FISHERMAN_ANDREW_2                 366
#define TRAINER_FISHERMAN_ANDREW_3                 367
#define TRAINER_PICNICKER_ALMA                     368
#define TRAINER_PICNICKER_ALMA_2                   369
#define TRAINER_PICNICKER_ALMA_3                   370
#define TRAINER_BIRD_KEEPER_SEBASTIAN              371
#define TRAINER_BIRD_KEEPER_SEBASTIAN_2            372
#define TRAINER_BIRD_KEEPER_SEBASTIAN_3            373
#define TRAINER_PICNICKER_SUSIE                    374
#define TRAINER_PICNICKER_SUSIE_2                  375
#define TRAINER_PICNICKER_SUSIE_3                  376
#define TRAINER_BEAUTY_LOLA                        377
#define TRAINER_BEAUTY_LOLA_2                      378
#define TRAINER_BEAUTY_LOLA_3                      379
#define TRAINER_BEAUTY_SHEILA                      380
#define TRAINER_BEAUTY_SHEILA_2                    381
#define TRAINER_BEAUTY_SHEILA_3                    382
#define TRAINER_PICNICKER_VALERIE                  383
#define TRAINER_PICNICKER_VALERIE_2                384
#define TRAINER_PICNICKER_VALERIE_3                385
#define TRAINER_PICNICKER_GWEN                     386
#define TRAINER_PICNICKER_GWEN_2                   387
#define TRAINER_PICNICKER_GWEN_3                   388
#define TRAINER_BIRD_KEEPER_ROBERT                 389
#define TRAINER_BIRD_KEEPER_ROBERT_2               390
#define TRAINER_BIRD_KEEPER_ROBERT_3               391
#define TRAINER_BIRD_KEEPER_PERRY                  392
#define TRAINER_BIRD_KEEPER_PERRY_2                393
#define TRAINER_BIRD_KEEPER_PERRY_3                394
#define TRAINER_BIKER_JARED                        395
#define TRAINER_BIKER_JARED_2                      396
#define TRAINER_BIKER_JARED_3                      397
#define TRAINER_BIRD_KEEPER_CARTER                 398
#define TRAINER_BIRD_KEEPER_CARTER_2               399
#define TRAINER_BIRD_KEEPER_CARTER_3               400
#define TRAINER_BIRD_KEEPER_MITCH                  401
#define TRAINER_BIRD_KEEPER_MITCH_2                402
#define TRAINER_BIRD_KEEPER_MITCH_3                403
#define TRAINER_BIRD_KEEPER_MARLON                 404
#define TRAINER_BIRD_KEEPER_MARLON_2               405
#define TRAINER_BIRD_KEEPER_MARLON_3               406
#define TRAINER_BIRD_KEEPER_BECK                   407
#define TRAINER_BIRD_KEEPER_BECK_2                 408
#define TRAINER_BIRD_KEEPER_BECK_3                 409
#define TRAINER_BIRD_KEEPER_DONALD                 410
#define TRAINER_BIRD_KEEPER_DONALD_2               411
#define TRAINER_BIRD_KEEPER_DONALD_3               412
#define TRAINER_BIRD_KEEPER_BENNY                  413
#define TRAINER_BIRD_KEEPER_BENNY_2                414
#define TRAINER_BIRD_KEEPER_BENNY_3                415
#define TRAINER_TWINS_KIRI_JAN                     416
#define TRAINER_TWINS_KIRI_JAN_2                   417
#define TRAINER_TWINS_KIRI_JAN_3                   418
#define TRAINER_BIKER_GERALD                       419
#define TRAINER_BIKER_GERALD_2                     420
#define TRAINER_BIKER_GERALD_3                     421
#define TRAINER_BIKER_MALIK                        422
#define TRAINER_BIKER_MALIK_2                      423
#define TRAINER_BIKER_MALIK_3                      424
#define TRAINER_BIKER_ISAAC                        425
#define TRAINER_BIKER_ISAAC_2                      426
#define TRAINER_BIKER_ISAAC_3                      427
#define TRAINER_BIKER_LUKAS                        428
#define TRAINER_BIKER_LUKAS_2                      429
#define TRAINER_BIKER_LUKAS_3                      430
#define TRAINER_PICNICKER_BECKY                    431
#define TRAINER_PICNICKER_BECKY_2                  432
#define TRAINER_PICNICKER_BECKY_3                  433
#define TRAINER_CRUSH_KIN_RON_MYA                  434
#define TRAINER_CRUSH_KIN_RON_MYA_2                435
#define TRAINER_CRUSH_KIN_RON_MYA_3                436
#define TRAINER_PICNICKER_CELIA                    437
#define TRAINER_PICNICKER_CELIA_2                  438
#define TRAINER_PICNICKER_CELIA_3                  439
#define TRAINER_BIKER_ERNEST                       440
#define TRAINER_BIKER_ERNEST_2                     441
#define TRAINER_BIKER_ERNEST_3                     442
#define TRAINER_BIKER_ALEX                         443
#define TRAINER_BIKER_ALEX_2                       444
#define TRAINER_BIKER_ALEX_3                       445
#define TRAINER_BEAUTY_GRACE                       446
#define TRAINER_BEAUTY_GRACE_2                     447
#define TRAINER_BEAUTY_GRACE_3                     448
#define TRAINER_BEAUTY_OLIVIA                      449
#define TRAINER_BEAUTY_OLIVIA_2                    450
#define TRAINER_BEAUTY_OLIVIA_3                    451
#define TRAINER_PICNICKER_KINDRA                   452
#define TRAINER_PICNICKER_KINDRA_2                 453
#define TRAINER_PICNICKER_KINDRA_3                 454
#define TRAINER_BIRD_KEEPER_CHESTER                455
#define TRAINER_BIRD_KEEPER_CHESTER_2              456
#define TRAINER_BIRD_KEEPER_CHESTER_3              457
#define TRAINER_BIRD_KEEPER_EDWIN                  458
#define TRAINER_BIRD_KEEPER_EDWIN_2                459
#define TRAINER_BIRD_KEEPER_EDWIN_3                460
#define TRAINER_PICNICKER_YAZMIN                   461
#define TRAINER_PICNICKER_YAZMIN_2                 462
#define TRAINER_PICNICKER_YAZMIN_3                 463
#define TRAINER_BIKER_LAO                          464
#define TRAINER_BIKER_LAO_2                        465
#define TRAINER_BIKER_LAO_3                        466
#define TRAINER_CUE_BALL_KOJI                      467
#define TRAINER_CUE_BALL_KOJI_2                    468
#define TRAINER_CUE_BALL_KOJI_3                    469
#define TRAINER_CUE_BALL_LUKE                      470
#define TRAINER_CUE_BALL_LUKE_2                    471
#define TRAINER_CUE_BALL_LUKE_3                    472
#define TRAINER_BIKER_HIDEO                        473
#define TRAINER_BIKER_HIDEO_2                      474
#define TRAINER_BIKER_HIDEO_3                      475
#define TRAINER_BIKER_RUBEN                        476
#define TRAINER_BIKER_RUBEN_2                      477
#define TRAINER_BIKER_RUBEN_3                      478
#define TRAINER_CUE_BALL_CAMRON                    479
#define TRAINER_CUE_BALL_CAMRON_2                  480
#define TRAINER_CUE_BALL_CAMRON_3                  481
#define TRAINER_CUE_BALL_ISAIAH                    482
#define TRAINER_CUE_BALL_ISAIAH_2                  483
#define TRAINER_CUE_BALL_ISAIAH_3                  484
#define TRAINER_BIKER_VIRGIL                       485
#define TRAINER_BIKER_VIRGIL_2                     486
#define TRAINER_BIKER_VIRGIL_3                     487
#define TRAINER_CUE_BALL_RAUL                      488
#define TRAINER_CUE_BALL_RAUL_2                    489
#define TRAINER_CUE_BALL_RAUL_3                    490
#define TRAINER_BIKER_BILLY                        491
#define TRAINER_BIKER_BILLY_2                      492
#define TRAINER_BIKER_BILLY_3                      493
#define TRAINER_CUE_BALL_JAMAL                     494
#define TRAINER_CUE_BALL_JAMAL_2                   495
#define TRAINER_CUE_BALL_JAMAL_3                   496
#define TRAINER_BIKER_NIKOLAS                      497
#define TRAINER_BIKER_NIKOLAS_2                    498
#define TRAINER_BIKER_NIKOLAS_3                    499
#define TRAINER_CUE_BALL_ZEEK                      500
#define TRAINER_CUE_BALL_ZEEK_2                    501
#define TRAINER_CUE_BALL_ZEEK_3                    502
#define TRAINER_CUE_BALL_COREY                     503
#define TRAINER_CUE_BALL_COREY_2                   504
#define TRAINER_CUE_BALL_COREY_3                   505
#define TRAINER_BIKER_JAXON                        506
#define TRAINER_BIKER_JAXON_2                      507
#define TRAINER_BIKER_JAXON_3                      508
#define TRAINER_BIKER_WILLIAM                      509
#define TRAINER_BIKER_WILLIAM_2                    510
#define TRAINER_BIKER_WILLIAM_3                    511
#define TRAINER_BIRD_KEEPER_JACOB                  512
#define TRAINER_BIRD_KEEPER_JACOB_2                513
#define TRAINER_BIRD_KEEPER_JACOB_3                514
#define TRAINER_BIRD_KEEPER_WILTON                 515
#define TRAINER_BIRD_KEEPER_WILTON_2               516
#define TRAINER_BIRD_KEEPER_WILTON_3               517
#define TRAINER_BIRD_KEEPER_RAMIRO                 518
#define TRAINER_BIRD_KEEPER_RAMIRO_2               519
#define TRAINER_BIRD_KEEPER_RAMIRO_3               520
#define TRAINER_JUGGLER_NATE                       521
#define TRAINER_JUGGLER_KAYDEN                     522
#define TRAINER_JUGGLER_KIRK                       523
#define TRAINER_TAMER_EDGAR                        524
#define TRAINER_TAMER_PHIL                         525
#define TRAINER_JUGGLER_SHAWN                      526
#define TRAINER_BLACK_BELT_HITOSHI                 527
#define TRAINER_BLACK_BELT_HIDEKI                  528
#define TRAINER_BLACK_BELT_AARON                   529
#define TRAINER_BLACK_BELT_MIKE                    530
#define TRAINER_BLACK_BELT_KOICHI                  531
#define TRAINER_TEAM_ROCKET_GRUNT_23               532
#define TRAINER_TEAM_ROCKET_GRUNT_24               533
#define TRAINER_SCIENTIST_JERRY                    534
#define TRAINER_SCIENTIST_CONNOR                   535
#define TRAINER_TEAM_ROCKET_GRUNT_25               536
#define TRAINER_SCIENTIST_JOSE                     537
#define TRAINER_TEAM_ROCKET_GRUNT_26               538
#define TRAINER_TEAM_ROCKET_GRUNT_27               539
#define TRAINER_SCIENTIST_RODNEY                   540
#define TRAINER_TEAM_ROCKET_GRUNT_28               541
#define TRAINER_TEAM_ROCKET_GRUNT_29               542
#define TRAINER_SCIENTIST_BEAU                     543
#define TRAINER_JUGGLER_DALTON                     544
#define TRAINER_TEAM_ROCKET_GRUNT_30               545
#define TRAINER_TEAM_ROCKET_GRUNT_31               546
#define TRAINER_SCIENTIST_TAYLOR                   547
#define TRAINER_TEAM_ROCKET_GRUNT_33               548
#define TRAINER_TEAM_ROCKET_GRUNT_34               549
#define TRAINER_TEAM_ROCKET_GRUNT_35               550
#define TRAINER_SCIENTIST_JOSHUA                   551
#define TRAINER_TEAM_ROCKET_GRUNT_32               552
#define TRAINER_TEAM_ROCKET_GRUNT_36               553
#define TRAINER_SCIENTIST_PARKER                   554
#define TRAINER_TEAM_ROCKET_GRUNT_37               555
#define TRAINER_TEAM_ROCKET_GRUNT_38               556
#define TRAINER_SCIENTIST_ED                       557
#define TRAINER_TEAM_ROCKET_GRUNT_39               558
#define TRAINER_SCIENTIST_TRAVIS                   559
#define TRAINER_TEAM_ROCKET_GRUNT_40               560
#define TRAINER_TEAM_ROCKET_GRUNT_41               561
#define TRAINER_RIVAL_SILPH_SQUIRTLE               562
#define TRAINER_RIVAL_SILPH_BULBASAUR              563
#define TRAINER_RIVAL_SILPH_CHARMANDER             564
#define TRAINER_BOSS_GIOVANNI_2                    565
#define TRAINER_PSYCHIC_JOHAN                      566
#define TRAINER_CHANNELER_AMANDA                   567
#define TRAINER_PSYCHIC_TYRON                      568
#define TRAINER_CHANNELER_STACY                    569
#define TRAINER_PSYCHIC_CAMERON                    570
#define TRAINER_CHANNELER_TASHA                    571
#define TRAINER_PSYCHIC_PRESTON                    572
#define TRAINER_SWIMMER_MALE_RICHARD               573
#define TRAINER_SWIMMER_MALE_RICHARD_2             574
#define TRAINER_SWIMMER_MALE_RICHARD_3             575
#define TRAINER_SWIMMER_MALE_REECE                 576
#define TRAINER_SWIMMER_MALE_REECE_2               577
#define TRAINER_SWIMMER_MALE_REECE_3               578
#define TRAINER_SWIMMER_MALE_TONY                  579
#define TRAINER_SWIMMER_MALE_TONY_2                580
#define TRAINER_SWIMMER_MALE_TONY_3                581
#define TRAINER_SWIMMER_MALE_DAVID                 582
#define TRAINER_SWIMMER_MALE_DAVID_2               583
#define TRAINER_SWIMMER_MALE_DAVID_3               584
#define TRAINER_SWIMMER_MALE_DOUGLAS               585
#define TRAINER_SWIMMER_MALE_DOUGLAS_2             586
#define TRAINER_SWIMMER_MALE_DOUGLAS_3             587
#define TRAINER_SWIMMER_MALE_MATTHEW               588
#define TRAINER_SWIMMER_MALE_MATTHEW_2             589
#define TRAINER_SWIMMER_MALE_MATTHEW_3             590
#define TRAINER_SIS_AND_BRO_LIA_LUC                591
#define TRAINER_SIS_AND_BRO_LIA_LUC_2              592
#define TRAINER_SIS_AND_BRO_LIA_LUC_3              593
#define TRAINER_SWIMMER_MALE_AXLE                  594
#define TRAINER_SWIMMER_MALE_AXLE_2                595
#define TRAINER_SWIMMER_MALE_AXLE_3                596
#define TRAINER_SWIMMER_FEMALE_ALICE               597
#define TRAINER_SWIMMER_FEMALE_ALICE_2             598
#define TRAINER_SWIMMER_FEMALE_ALICE_3             599
#define TRAINER_SWIMMER_FEMALE_CONNIE              600
#define TRAINER_SWIMMER_FEMALE_CONNIE_2            601
#define TRAINER_SWIMMER_FEMALE_CONNIE_3            602
#define TRAINER_SWIMMER_FEMALE_ANYA                603
#define TRAINER_SWIMMER_FEMALE_ANYA_2              604
#define TRAINER_SWIMMER_FEMALE_ANYA_3              605
#define TRAINER_SWIMMER_MALE_BARRY                 606
#define TRAINER_SWIMMER_MALE_BARRY_2               607
#define TRAINER_SWIMMER_MALE_BARRY_3               608
#define TRAINER_SWIMMER_MALE_DARRIN                609
#define TRAINER_SWIMMER_MALE_DARRIN_2              610
#define TRAINER_SWIMMER_MALE_DARRIN_3              611
#define TRAINER_SWIMMER_FEMALE_SHIRLEY             612
#define TRAINER_SWIMMER_FEMALE_SHIRLEY_2           613
#define TRAINER_SWIMMER_FEMALE_SHIRLEY_3           614
#define TRAINER_SWIMMER_FEMALE_TIFFANY             615
#define TRAINER_SWIMMER_FEMALE_TIFFANY_2           616
#define TRAINER_SWIMMER_FEMALE_TIFFANY_3           617
#define TRAINER_PICNICKER_IRENE                    618
#define TRAINER_PICNICKER_IRENE_2                  619
#define TRAINER_PICNICKER_IRENE_3                  620
#define TRAINER_BIRD_KEEPER_ROGER                  621
#define TRAINER_BIRD_KEEPER_ROGER_2                622
#define TRAINER_BIRD_KEEPER_ROGER_3                623
#define TRAINER_SWIMMER_FEMALE_NORA                624
#define TRAINER_SWIMMER_FEMALE_NORA_2              625
#define TRAINER_SWIMMER_FEMALE_NORA_3              626
#define TRAINER_SWIMMER_MALE_DEAN                  627
#define TRAINER_SWIMMER_MALE_DEAN_2                628
#define TRAINER_SWIMMER_MALE_DEAN_3                629
#define TRAINER_PICNICKER_MISSY                    630
#define TRAINER_PICNICKER_MISSY_2                  631
#define TRAINER_PICNICKER_MISSY_3                  632
#define TRAINER_SWIMMER_FEMALE_MELISSA             633
#define TRAINER_SWIMMER_FEMALE_MELISSA_2           634
#define TRAINER_SWIMMER_FEMALE_MELISSA_3           635
#define TRAINER_FISHERMAN_RONALD                   636
#define TRAINER_FISHERMAN_RONALD_2                 637
#define TRAINER_FISHERMAN_RONALD_3                 638
#define TRAINER_FISHERMAN_WADE                     639
#define TRAINER_FISHERMAN_WADE_2                   640
#define TRAINER_FISHERMAN_WADE_3                   641
#define TRAINER_SIS_AND_BRO_LIL_IAN                642
#define TRAINER_SIS_AND_BRO_LIL_IAN_2              643
#define TRAINER_SIS_AND_BRO_LIL_IAN_3              644
#define TRAINER_SWIMMER_MALE_SPENCER               645
#define TRAINER_SWIMMER_MALE_SPENCER_2             646
#define TRAINER_SWIMMER_MALE_SPENCER_3             647
#define TRAINER_FISHERMAN_CLAUDE                   648
#define TRAINER_FISHERMAN_CLAUDE_2                 649
#define TRAINER_FISHERMAN_CLAUDE_3                 650
#define TRAINER_FISHERMAN_NOLAN                    651
#define TRAINER_FISHERMAN_NOLAN_2                  652
#define TRAINER_FISHERMAN_NOLAN_3                  653
#define TRAINER_SWIMMER_MALE_JACK                  654
#define TRAINER_SWIMMER_MALE_JACK_2                655
#define TRAINER_SWIMMER_MALE_JACK_3                656
#define TRAINER_SWIMMER_MALE_ROLAND                657
#define TRAINER_SWIMMER_MALE_ROLAND_2              658
#define TRAINER_SWIMMER_MALE_ROLAND_3              659
#define TRAINER_SWIMMER_MALE_JEROME                660
#define TRAINER_SWIMMER_MALE_JEROME_2              661
#define TRAINER_SWIMMER_MALE_JEROME_3              662
#define TRAINER_YOUNGSTER_JOHNSON                  663
#define TRAINER_BURGLAR_ARNIE                      664
#define TRAINER_BURGLAR_SIMON                      665
#define TRAINER_SCIENTIST_BRAYDON                  666
#define TRAINER_SCIENTIST_TED                      667
#define TRAINER_BURGLAR_LEWIS                      668
#define TRAINER_SCIENTIST_IVAN                     669
#define TRAINER_BURGLAR_QUINN                      670
#define TRAINER_SUPER_NERD_ERIK                    671
#define TRAINER_SUPER_NERD_AVERY                   672
#define TRAINER_BURGLAR_RAMON                      673
#define TRAINER_SUPER_NERD_DEREK                   674
#define TRAINER_BURGLAR_DUSTY                      675
#define TRAINER_SUPER_NERD_ZAC                     676
#define TRAINER_TAMER_COLE                         677
#define TRAINER_BLACK_BELT_KIYO                    678
#define TRAINER_COOLTRAINER_SAMUEL                 679
#define TRAINER_COOLTRAINER_YUJI                   680
#define TRAINER_BLACK_BELT_ATSUSHI                 681
#define TRAINER_TAMER_JASON                        682
#define TRAINER_COOLTRAINER_WARREN                 683
#define TRAINER_BLACK_BELT_TAKASHI                 684
#define TRAINER_RIVAL_ROUTE22_LATE_SQUIRTLE        685
#define TRAINER_RIVAL_ROUTE22_LATE_BULBASAUR       686
#define TRAINER_RIVAL_ROUTE22_LATE_CHARMANDER      687
#define TRAINER_COOLTRAINER_NAOMI                  688
#define TRAINER_COOLTRAINER_ROLANDO                689
#define TRAINER_BLACK_BELT_DAISUKE                 690
#define TRAINER_JUGGLER_NELSON                     691
#define TRAINER_TAMER_VINCENT                      692
#define TRAINER_JUGGLER_GREGORY                    693
#define TRAINER_COOLTRAINER_GEORGE                 694
#define TRAINER_POKEMANIAC_DAWSON                  695
#define TRAINER_COOLTRAINER_ALEXA                  696
#define TRAINER_COOLTRAINER_COLBY                  697
#define TRAINER_COOLTRAINER_CAROLINE               698
#define TRAINER_COOL_COUPLE_RAY_TYRA               699
#define TRAINER_ELITE_FOUR_LORELEI                 700
#define TRAINER_ELITE_FOUR_LORELEI_2               701
#define TRAINER_ELITE_FOUR_BRUNO                   702
#define TRAINER_ELITE_FOUR_BRUNO_2                 703
#define TRAINER_ELITE_FOUR_AGATHA                  704
#define TRAINER_ELITE_FOUR_AGATHA_2                705
#define TRAINER_ELITE_FOUR_LANCE                   706
#define TRAINER_ELITE_FOUR_LANCE_2                 707
#define TRAINER_CHAMPION_FIRST_SQUIRTLE            708
#define TRAINER_CHAMPION_FIRST_BULBASAUR           709
#define TRAINER_CHAMPION_FIRST_CHARMANDER          710
#define TRAINER_CHAMPION_REMATCH_SQUIRTLE          711
#define TRAINER_CHAMPION_REMATCH_BULBASAUR         712
#define TRAINER_CHAMPION_REMATCH_CHARMANDER        713
#define TRAINER_SWIMMER_FEMALE_AMARA               714
#define TRAINER_SWIMMER_FEMALE_AMARA_2             715
#define TRAINER_SWIMMER_FEMALE_AMARA_3             716
#define TRAINER_SWIMMER_FEMALE_ABIGAIL             717
#define TRAINER_SWIMMER_FEMALE_ABIGAIL_2           718
#define TRAINER_SWIMMER_FEMALE_ABIGAIL_3           719
#define TRAINER_PICNICKER_CLAIRE                   720
#define TRAINER_PICNICKER_CLAIRE_2                 721
#define TRAINER_PICNICKER_CLAIRE_3                 722
#define TRAINER_CAMPER_BRYCE                       723
#define TRAINER_CAMPER_BRYCE_2                     724
#define TRAINER_CAMPER_BRYCE_3                     725
#define TRAINER_CRUSH_GIRL_TANYA                   726
#define TRAINER_CRUSH_GIRL_TANYA_2                 727
#define TRAINER_CRUSH_GIRL_TANYA_3                 728
#define TRAINER_SWIMMER_MALE_GARRETT               729
#define TRAINER_SWIMMER_MALE_GARRETT_2             730
#define TRAINER_SWIMMER_MALE_GARRETT_3             731
#define TRAINER_CRUSH_KIN_MIK_KIA                  732
#define TRAINER_CRUSH_KIN_MIK_KIA_2                733
#define TRAINER_CRUSH_KIN_MIK_KIA_3                734
#define TRAINER_BLACK_BELT_HUGH                    735
#define TRAINER_BLACK_BELT_HUGH_2                  736
#define TRAINER_BLACK_BELT_HUGH_3                  737
#define TRAINER_BLACK_BELT_SHEA                    738
#define TRAINER_BLACK_BELT_SHEA_2                  739
#define TRAINER_BLACK_BELT_SHEA_3                  740
#define TRAINER_CRUSH_GIRL_SHARON                  741
#define TRAINER_CRUSH_GIRL_SHARON_2                742
#define TRAINER_CRUSH_GIRL_SHARON_3                743
#define TRAINER_SWIMMER_MALE_FINN                  744
#define TRAINER_SWIMMER_MALE_FINN_2                745
#define TRAINER_SWIMMER_MALE_FINN_3                746
#define TRAINER_SWIMMER_FEMALE_MARIA               747
#define TRAINER_SWIMMER_FEMALE_MARIA_2             748
#define TRAINER_SWIMMER_FEMALE_MARIA_3             749
#define TRAINER_FISHERMAN_TOMMY                    750
#define TRAINER_FISHERMAN_TOMMY_2                  751
#define TRAINER_FISHERMAN_TOMMY_3                  752
#define TRAINER_BIKER_GOON                         753
#define TRAINER_BIKER_GOON_2                       754
#define TRAINER_BIKER_GOON_3                       755
#define TRAINER_CUE_BALL_PAXTON                    756
#define TRAINER_TWINS_JOY_MEG                      757
#define TRAINER_TWINS_JOY_MEG_2                    758
#define TRAINER_TWINS_JOY_MEG_3                    759
#define TRAINER_AROMA_LADY_VIOLET                  760
#define TRAINER_AROMA_LADY_VIOLET_2                761
#define TRAINER_AROMA_LADY_VIOLET_3                762
#define TRAINER_TUBER_ALEXIS                       763
#define TRAINER_TUBER_ALEXIS_2                     764
#define TRAINER_TUBER_ALEXIS_3                     765
#define TRAINER_SWIMMER_FEMALE_TISHA               766
#define TRAINER_SWIMMER_FEMALE_TISHA_2             767
#define TRAINER_SWIMMER_FEMALE_TISHA_3             768
#define TRAINER_TUBER_AMIRA                        769
#define TRAINER_TUBER_AMIRA_2                      770
#define TRAINER_TUBER_AMIRA_3                      771
#define TRAINER_AROMA_LADY_NIKKI                   772
#define TRAINER_AROMA_LADY_NIKKI_2                 773
#define TRAINER_AROMA_LADY_NIKKI_3                 774
#define TRAINER_TEAM_ROCKET_GRUNT_43               775
#define TRAINER_TEAM_ROCKET_GRUNT_44               776
#define TRAINER_PKMN_RANGER_BETH                   777
#define TRAINER_CRUSH_GIRL_JOCELYN                 778
#define TRAINER_PKMN_RANGER_LOGAN                  779
#define TRAINER_TEAM_ROCKET_GRUNT_45               780
#define TRAINER_TEAM_ROCKET_GRUNT_49               781
#define TRAINER_TEAM_ROCKET_GRUNT_50               782
#define TRAINER_TEAM_ROCKET_GRUNT_51               783
#define TRAINER_BIRD_KEEPER_MILO                   784
#define TRAINER_BIRD_KEEPER_MILO_2                 785
#define TRAINER_BIRD_KEEPER_MILO_3                 786
#define TRAINER_BIRD_KEEPER_CHAZ                   787
#define TRAINER_BIRD_KEEPER_CHAZ_2                 788
#define TRAINER_BIRD_KEEPER_CHAZ_3                 789
#define TRAINER_BIRD_KEEPER_HAROLD                 790
#define TRAINER_BIRD_KEEPER_HAROLD_2               791
#define TRAINER_BIRD_KEEPER_HAROLD_3               792
#define TRAINER_PKMN_BREEDER_ALIZE                 793
#define TRAINER_PKMN_BREEDER_ALIZE_2               794
#define TRAINER_PKMN_BREEDER_ALIZE_3               795
#define TRAINER_PAINTER_RAYNA                      796
#define TRAINER_PAINTER_RAYNA_2                    797
#define TRAINER_PAINTER_RAYNA_3                    798
#define TRAINER_LADY_JACKI                         799
#define TRAINER_LADY_JACKI_2                       800
#define TRAINER_LADY_JACKI_3                       801
#define TRAINER_PAINTER_CELINA                     802
#define TRAINER_PAINTER_CELINA_2                   803
#define TRAINER_PAINTER_CELINA_3                   804
#define TRAINER_LADY_GILLIAN                       805
#define TRAINER_LADY_GILLIAN_2                     806
#define TRAINER_LADY_GILLIAN_3                     807
#define TRAINER_PAINTER_DAISY                      808
#define TRAINER_PAINTER_DAISY_2                    809
#define TRAINER_PAINTER_DAISY_3                    810
#define TRAINER_YOUNGSTER_DESTIN                   811
#define TRAINER_YOUNGSTER_DESTIN_2                 812
#define TRAINER_YOUNGSTER_DESTIN_3                 813
#define TRAINER_SWIMMER_MALE_TOBY                  814
#define TRAINER_SWIMMER_MALE_TOBY_2                815
#define TRAINER_SWIMMER_MALE_TOBY_3                816
#define TRAINER_RUIN_MANIAC_LAWSON                 817
#define TRAINER_PSYCHIC_LAURA                      818
#define TRAINER_LADY_SELPHY                        819
#define TRAINER_JUGGLER_EDWARD                     820
#define TRAINER_JUGGLER_EDWARD_2                   821
#define TRAINER_JUGGLER_EDWARD_3                   822
#define TRAINER_HIKER_EARL                         823
#define TRAINER_HIKER_EARL_2                       824
#define TRAINER_HIKER_EARL_3                       825
#define TRAINER_SWIMMER_FEMALE_DENISE              826
#define TRAINER_SWIMMER_FEMALE_DENISE_2            827
#define TRAINER_SWIMMER_FEMALE_DENISE_3            828
#define TRAINER_SWIMMER_MALE_SAMIR                 829
#define TRAINER_SWIMMER_MALE_SAMIR_2               830
#define TRAINER_SWIMMER_MALE_SAMIR_3               831
#define TRAINER_TWINS_MIU_MIA                      832
#define TRAINER_TWINS_MIU_MIA_2                    833
#define TRAINER_TWINS_MIU_MIA_3                    834
#define TRAINER_AROMA_LADY_ROSE                    835
#define TRAINER_AROMA_LADY_ROSE_2                  836
#define TRAINER_AROMA_LADY_ROSE_3                  837
#define TRAINER_YOUNGSTER_CORDELL                  838
#define TRAINER_PKMN_BREEDER_BETHANY               839
#define TRAINER_BUG_CATCHER_GARRET                 840
#define TRAINER_LASS_JOANA                         841
#define TRAINER_BUG_CATCHER_VANCE                  842
#define TRAINER_YOUNGSTER_NASH                     843
#define TRAINER_RUIN_MANIAC_LAYTON                 844
#define TRAINER_PICNICKER_MARCY                    845
#define TRAINER_BUG_CATCHER_JONAH                  846
#define TRAINER_PKMN_BREEDER_ALLISON               847
#define TRAINER_LASS_DALIA                         848
#define TRAINER_CAMPER_RILEY                       849
#define TRAINER_PSYCHIC_JACLYN                     850
#define TRAINER_PSYCHIC_JACLYN_2                   851
#define TRAINER_PSYCHIC_JACLYN_3                   852
#define TRAINER_SWIMMER_FEMALE_NICOLE              853
#define TRAINER_SWIMMER_FEMALE_NICOLE_2            854
#define TRAINER_SWIMMER_FEMALE_NICOLE_3            855
#define TRAINER_SIS_AND_BRO_AVA_GEB                856
#define TRAINER_SIS_AND_BRO_AVA_GEB_2              857
#define TRAINER_SIS_AND_BRO_AVA_GEB_3              858
#define TRAINER_SWIMMER_MALE_MYMO                  859
#define TRAINER_SWIMMER_MALE_MYMO_2                860
#define TRAINER_SWIMMER_MALE_MYMO_3                861
#define TRAINER_FISHERMAN_TYLOR                    862
#define TRAINER_FISHERMAN_TYLOR_2                  863
#define TRAINER_FISHERMAN_TYLOR_3                  864
#define TRAINER_TEAM_ROCKET_GRUNT_46               865
#define TRAINER_HIKER_DARYL                        866
#define TRAINER_HIKER_DARYL_2                      867
#define TRAINER_HIKER_DARYL_3                      868
#define TRAINER_POKEMANIAC_HECTOR                  869
#define TRAINER_POKEMANIAC_HECTOR_2                870
#define TRAINER_POKEMANIAC_HECTOR_3                871
#define TRAINER_RUIN_MANIAC_STANLY                 872
#define TRAINER_RUIN_MANIAC_STANLY_2               873
#define TRAINER_RUIN_MANIAC_STANLY_3               874
#define TRAINER_RUIN_MANIAC_FOSTER                 875
#define TRAINER_RUIN_MANIAC_FOSTER_2               876
#define TRAINER_RUIN_MANIAC_FOSTER_3               877
#define TRAINER_RUIN_MANIAC_LARRY                  878
#define TRAINER_RUIN_MANIAC_LARRY_2                879
#define TRAINER_RUIN_MANIAC_LARRY_3                880
#define TRAINER_TEAM_ROCKET_GRUNT_42               881
#define TRAINER_TEAM_ROCKET_GRUNT_47               882
#define TRAINER_TEAM_ROCKET_GRUNT_48               883
#define TRAINER_TEAM_ROCKET_ADMIN                  884
#define TRAINER_TEAM_ROCKET_ADMIN_2                885
#define TRAINER_SCIENTIST_GIDEON                   886
#define TRAINER_PSYCHIC_RODETTE                    887
#define TRAINER_PSYCHIC_RODETTE_2                  888
#define TRAINER_PSYCHIC_RODETTE_3                  889
#define TRAINER_PSYCHIC_DARIO                      890
#define TRAINER_PSYCHIC_DARIO_2                    891
#define TRAINER_PSYCHIC_DARIO_3                    892
#define TRAINER_AROMA_LADY_MIAH                    893
#define TRAINER_AROMA_LADY_MIAH_2                  894
#define TRAINER_AROMA_LADY_MIAH_3                  895
#define TRAINER_JUGGLER_MASON                      896
#define TRAINER_JUGGLER_MASON_2                    897
#define TRAINER_JUGGLER_MASON_3                    898
#define TRAINER_PKMN_RANGER_NICOLAS                899
#define TRAINER_PKMN_RANGER_NICOLAS_2              900
#define TRAINER_PKMN_RANGER_NICOLAS_3              901
#define TRAINER_PKMN_RANGER_MADELINE               902
#define TRAINER_PKMN_RANGER_MADELINE_2             903
#define TRAINER_PKMN_RANGER_MADELINE_3             904
#define TRAINER_YOUNG_COUPLE_EVE_JON               905
#define TRAINER_YOUNG_COUPLE_EVE_JON_2             906
#define TRAINER_YOUNG_COUPLE_EVE_JON_3             907
#define TRAINER_COOL_COUPLE_LEX_NYA                908
#define TRAINER_COOL_COUPLE_LEX_NYA_2              909
#define TRAINER_COOL_COUPLE_LEX_NYA_3              910
#define TRAINER_TAMER_EVAN                         911
#define TRAINER_TAMER_EVAN_2                       912
#define TRAINER_TAMER_EVAN_3                       913
#define TRAINER_PKMN_RANGER_JACKSON                914
#define TRAINER_PKMN_RANGER_JACKSON_2              915
#define TRAINER_PKMN_RANGER_JACKSON_3              916
#define TRAINER_PKMN_RANGER_KATELYN                917
#define TRAINER_PKMN_RANGER_KATELYN_2              918
#define TRAINER_PKMN_RANGER_KATELYN_3              919
#define TRAINER_CRUSH_GIRL_CYNDY                   920
#define TRAINER_CRUSH_GIRL_CYNDY_2                 921
#define TRAINER_CRUSH_GIRL_CYNDY_3                 922
#define TRAINER_COOLTRAINER_LEROY                  923
#define TRAINER_COOLTRAINER_LEROY_2                924
#define TRAINER_COOLTRAINER_LEROY_3                925
#define TRAINER_COOLTRAINER_MICHELLE               926
#define TRAINER_COOLTRAINER_MICHELLE_2             927
#define TRAINER_COOLTRAINER_MICHELLE_3             928
#define TRAINER_RUIN_MANIAC_BRANDON                929
#define TRAINER_RUIN_MANIAC_BRANDON_2              930
#define TRAINER_RUIN_MANIAC_BRANDON_3              931
#define TRAINER_GENTLEMAN_CLIFFORD                 932
#define TRAINER_GENTLEMAN_CLIFFORD_2               933
#define TRAINER_GENTLEMAN_CLIFFORD_3               934
#define TRAINER_PAINTER_EDNA                       935
#define TRAINER_PAINTER_EDNA_2                     936
#define TRAINER_PAINTER_EDNA_3                     937
#define TRAINER_RUIN_MANIAC_BENJAMIN               938
#define TRAINER_RUIN_MANIAC_BENJAMIN_2             939
#define TRAINER_RUIN_MANIAC_BENJAMIN_3             940
#define TRAINER_TEAM_ROCKET_GRUNT_22               941
#define TRAINER_LEADER_JANINE                      942
#define TRAINER_LEADER_JANINE_2                    943
#define TRAINER_LEADER_WILL                        944
#define TRAINER_LEADER_WILL_2                      945
#define TRAINER_LEADER_KAREN                       946
#define TRAINER_LEADER_KAREN_2                     947
#define TRAINER_PKMN_PROF_PROF_OAK                 948
#define TRAINER_PKMN_PROF_PROF_OAK_2               949

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is 
//       only space for 25 additional trainers before trainer flag space overflows.
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define NUM_TRAINERS                             950
#define MAX_TRAINERS_COUNT                       950

#endif  // GUARD_CONSTANTS_OPPONENTS_H
