Route2_EventScript_ItemEther::
	finditem ITEM_POKE_BALL
	end

Route2_EventScript_ItemParalyzeHeal::
	finditem ITEM_POKE_BALL
	end

ViridianForest_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

ViridianForest_EventScript_ItemAntidote::
	finditem ITEM_POKE_BALL
	end

ViridianForest_EventScript_ItemPotion::
	finditem ITEM_POKE_BALL
	end

MtMoon_1F_EventScript_ItemParalyzeHeal::
	finditem ITEM_POKE_BALL
	end

MtMoon_1F_EventScript_ItemTM09::
	finditem ITEM_POKE_BALL
	end

MtMoon_1F_EventScript_ItemPotion::
	finditem ITEM_POKE_BALL
	end

MtMoon_1F_EventScript_ItemRareCandy::
	finditem ITEM_POKE_BALL
	end

MtMoon_1F_EventScript_ItemEscapeRope::
	finditem ITEM_POKE_BALL
	end

MtMoon_1F_EventScript_ItemMoonStone::
	finditem ITEM_POKE_BALL
	end

MtMoon_B2F_EventScript_ItemStarPiece::
	finditem ITEM_POKE_BALL
	end

MtMoon_B2F_EventScript_ItemTM46::
	finditem ITEM_POKE_BALL
	end

Route4_EventScript_ItemTM05::
	finditem ITEM_POKE_BALL
	end

Route24_EventScript_ItemTM45::
	finditem ITEM_POKE_BALL
	end

Route25_EventScript_ItemTM43::
	finditem ITEM_POKE_BALL
	end

SSAnne_1F_Room2_EventScript_ItemTM31::
	finditem ITEM_POKE_BALL
	end

SSAnne_2F_Room2_EventScript_ItemStardust::
	finditem ITEM_POKE_BALL
	end

SSAnne_2F_Room4_EventScript_ItemXAttack::
	finditem ITEM_POKE_BALL
	end

SSAnne_B1F_Room2_EventScript_ItemTM44::
	finditem ITEM_POKE_BALL
	end

SSAnne_B1F_Room3_EventScript_ItemEther::
	finditem ITEM_POKE_BALL
	end

SSAnne_B1F_Room5_EventScript_ItemSuperPotion::
	finditem ITEM_POKE_BALL
	end

SSAnne_Kitchen_EventScript_ItemGreatBall::
	finditem ITEM_POKE_BALL
	end

Route9_EventScript_ItemTM40::
	finditem ITEM_POKE_BALL
	end

RocketHideout_B1F_EventScript_ItemEscapeRope::
	finditem ITEM_POKE_BALL
	end

RocketHideout_B1F_EventScript_ItemHyperPotion::
	finditem ITEM_POKE_BALL
	end

RocketHideout_B2F_EventScript_ItemXSpeed::
	finditem ITEM_POKE_BALL
	end

RocketHideout_B2F_EventScript_ItemMoonStone::
	finditem ITEM_POKE_BALL
	end

RocketHideout_B2F_EventScript_ItemTM12::
	finditem ITEM_POKE_BALL
	end

RocketHideout_B2F_EventScript_ItemSuperPotion::
	finditem ITEM_POKE_BALL
	end

RocketHideout_B3F_EventScript_ItemRareCandy::
	finditem ITEM_POKE_BALL
	end

RocketHideout_B3F_EventScript_ItemTM21::
	finditem ITEM_POKE_BALL
	end

RocketHideout_B4F_EventScript_ItemTM49::
	finditem ITEM_POKE_BALL
	end

RocketHideout_B4F_EventScript_ItemMaxEther::
	finditem ITEM_POKE_BALL
	end

RocketHideout_B4F_EventScript_ItemCalcium::
	finditem ITEM_POKE_BALL
	end

PokemonTower_3F_EventScript_ItemEscapeRope::
	finditem ITEM_POKE_BALL
	end

PokemonTower_4F_EventScript_ItemElixir::
	finditem ITEM_POKE_BALL
	end

PokemonTower_4F_EventScript_ItemAwakening::
	finditem ITEM_POKE_BALL
	end

PokemonTower_4F_EventScript_ItemGreatBall::
	finditem ITEM_POKE_BALL
	end

PokemonTower_5F_EventScript_ItemNugget::
	finditem ITEM_POKE_BALL
	end

PokemonTower_6F_EventScript_ItemRareCandy::
	finditem ITEM_POKE_BALL
	end

PokemonTower_6F_EventScript_ItemXAccuracy::
	finditem ITEM_POKE_BALL
	end

Route12_EventScript_ItemTM48::
	finditem ITEM_POKE_BALL
	end

Route12_EventScript_ItemIron::
	finditem ITEM_POKE_BALL
	end

Route15_EventScript_ItemTM18::
	finditem ITEM_POKE_BALL
	end

SafariZone_Center_EventScript_ItemNugget::
	finditem ITEM_POKE_BALL
	end

SafariZone_East_EventScript_ItemMaxPotion::
	finditem ITEM_POKE_BALL
	end

SafariZone_East_EventScript_ItemFullRestore::
	finditem ITEM_POKE_BALL
	end

SafariZone_East_EventScript_ItemTM11::
	finditem ITEM_POKE_BALL
	end

SafariZone_East_EventScript_ItemLeafStone::
	finditem ITEM_POKE_BALL
	end

SafariZone_North_EventScript_ItemProtein::
	finditem ITEM_POKE_BALL
	end

SafariZone_North_EventScript_ItemTM47::
	finditem ITEM_POKE_BALL
	end

SafariZone_West_EventScript_ItemTM32::
	finditem ITEM_POKE_BALL
	end

SafariZone_West_EventScript_ItemGoldTeeth::
	finditem ITEM_GOLD_TEETH
	end

SafariZone_West_EventScript_ItemMaxPotion::
	finditem ITEM_POKE_BALL
	end

SafariZone_West_EventScript_ItemMaxRevive::
	finditem ITEM_POKE_BALL
	end

SilphCo_3F_EventScript_ItemHyperPotion::
	finditem ITEM_POKE_BALL
	end

SilphCo_4F_EventScript_ItemMaxRevive::
	finditem ITEM_POKE_BALL
	end

SilphCo_4F_EventScript_ItemEscapeRope::
	finditem ITEM_POKE_BALL
	end

SilphCo_4F_EventScript_ItemFullHeal::
	finditem ITEM_POKE_BALL
	end

SilphCo_5F_EventScript_ItemProtein::
	finditem ITEM_POKE_BALL
	end

SilphCo_5F_EventScript_ItemTM01::
	finditem ITEM_POKE_BALL
	end

SilphCo_5F_EventScript_ItemCardKey::
	finditem ITEM_CARD_KEY
	end

SilphCo_6F_EventScript_ItemHPUp::
	finditem ITEM_POKE_BALL
	end

SilphCo_6F_EventScript_ItemXSpecial::
	finditem ITEM_POKE_BALL
	end

SilphCo_7F_EventScript_ItemCalcium::
	finditem ITEM_POKE_BALL
	end

SilphCo_7F_EventScript_ItemTM08::
	finditem ITEM_POKE_BALL
	end

SilphCo_10F_EventScript_ItemCarbos::
	finditem ITEM_POKE_BALL
	end

SilphCo_10F_EventScript_ItemUltraBall::
	finditem ITEM_POKE_BALL
	end

SilphCo_10F_EventScript_ItemRareCandy::
	finditem ITEM_POKE_BALL
	end

PowerPlant_EventScript_ItemMaxPotion::
	finditem ITEM_POKE_BALL
	end

PowerPlant_EventScript_ItemTM17::
	finditem ITEM_POKE_BALL
	end

PowerPlant_EventScript_ItemTM25::
	finditem ITEM_POKE_BALL
	end

PowerPlant_EventScript_ItemThunderStone::
	finditem ITEM_POKE_BALL
	end

PowerPlant_EventScript_ItemElixir::
	finditem ITEM_POKE_BALL
	end

PokemonMansion_1F_EventScript_ItemCarbos::
	finditem ITEM_POKE_BALL
	end

PokemonMansion_1F_EventScript_ItemEscapeRope::
	finditem ITEM_POKE_BALL
	end

PokemonMansion_2F_EventScript_ItemCalcium::
	finditem ITEM_POKE_BALL
	end

PokemonMansion_3F_EventScript_ItemMaxPotion::
	finditem ITEM_POKE_BALL
	end

PokemonMansion_3F_EventScript_ItemIron::
	finditem ITEM_POKE_BALL
	end

PokemonMansion_B1F_EventScript_ItemTM14::
	finditem ITEM_POKE_BALL
	end

PokemonMansion_B1F_EventScript_ItemFullRestore::
	finditem ITEM_POKE_BALL
	end

PokemonMansion_B1F_EventScript_ItemTM22::
	finditem ITEM_POKE_BALL
	end

PokemonMansion_B1F_EventScript_ItemSecretKey::
	finditem ITEM_SECRET_KEY
	end

VictoryRoad_1F_EventScript_ItemRareCandy::
	finditem ITEM_POKE_BALL
	end

VictoryRoad_1F_EventScript_ItemTM02::
	finditem ITEM_POKE_BALL
	end

VictoryRoad_2F_EventScript_ItemGuardSpec::
	finditem ITEM_POKE_BALL
	end

VictoryRoad_2F_EventScript_ItemTM07::
	finditem ITEM_POKE_BALL
	end

VictoryRoad_2F_EventScript_ItemFullHeal::
	finditem ITEM_POKE_BALL
	end

VictoryRoad_2F_EventScript_ItemTM37::
	finditem ITEM_POKE_BALL
	end

VictoryRoad_3F_EventScript_ItemMaxRevive::
	finditem ITEM_POKE_BALL
	end

VictoryRoad_3F_EventScript_ItemTM50::
	finditem ITEM_POKE_BALL
	end

CeruleanCave_1F_EventScript_ItemMaxElixir::
	finditem ITEM_POKE_BALL
	end

CeruleanCave_1F_EventScript_ItemNugget::
	finditem ITEM_POKE_BALL
	end

CeruleanCave_1F_EventScript_ItemFullRestore::
	finditem ITEM_POKE_BALL
	end

CeruleanCave_2F_EventScript_ItemFullRestore::
	finditem ITEM_POKE_BALL
	end

CeruleanCave_2F_EventScript_ItemPPUp::
	finditem ITEM_POKE_BALL
	end

CeruleanCave_2F_EventScript_ItemUltraBall::
	finditem ITEM_POKE_BALL
	end

CeruleanCave_B1F_EventScript_ItemMaxRevive::
	finditem ITEM_POKE_BALL
	end

CeruleanCave_B1F_EventScript_ItemUltraBall::
	finditem ITEM_POKE_BALL
	end

FuchsiaCity_WardensHouse_EventScript_ItemRareCandy::
	finditem ITEM_QUICK_CLAW
	end

TwoIsland_EventScript_ItemRevive::
	finditem ITEM_POKE_BALL
	end

ThreeIsland_EventScript_ItemZinc::
	finditem ITEM_POKE_BALL
	end

ViridianForest_EventScript_ItemPotion2::
	finditem ITEM_POKE_BALL
	end

MtMoon_B2F_EventScript_ItemRevive::
	finditem ITEM_POKE_BALL
	end

MtMoon_B2F_EventScript_ItemAntidote::
	finditem ITEM_POKE_BALL
	end

Route11_EventScript_ItemXDefend::
	finditem ITEM_POKE_BALL
	end

Route9_EventScript_ItemBurnHeal::
	finditem ITEM_POKE_BALL
	end

RockTunnel_1F_EventScript_ItemRepel::
	finditem ITEM_POKE_BALL
	end

RockTunnel_1F_EventScript_ItemPearl::
	finditem ITEM_POKE_BALL
	end

RockTunnel_1F_EventScript_ItemEscapeRope::
	finditem ITEM_POKE_BALL
	end

RockTunnel_B1F_EventScript_ItemRevive::
	finditem ITEM_POKE_BALL
	end

RockTunnel_B1F_EventScript_ItemMaxEther::
	finditem ITEM_POKE_BALL
	end

SilphCo_8F_EventScript_ItemIron::
	finditem ITEM_POKE_BALL
	end

SilphCo_11F_EventScript_ItemZinc::
	finditem ITEM_POKE_BALL
	end

PokemonMansion_1F_EventScript_ItemProtein::
	finditem ITEM_POKE_BALL
	end

PokemonMansion_2F_EventScript_ItemZinc::
	finditem ITEM_POKE_BALL
	end

PokemonMansion_2F_EventScript_ItemHPUp::
	finditem ITEM_POKE_BALL
	end

ViridianCity_EventScript_ItemPotion::
	finditem ITEM_POKE_BALL
	end

Route11_EventScript_ItemGreatBall::
	finditem ITEM_POKE_BALL
	end

Route11_EventScript_ItemAwakening::
	finditem ITEM_POKE_BALL
	end

PokemonTower_5F_EventScript_ItemCleanseTag::
	finditem ITEM_CLEANSE_TAG
	end

CeladonCity_EventScript_ItemEther::
	finditem ITEM_POKE_BALL
	end

RocketHideout_B3F_EventScript_ItemBlackGlasses::
	finditem ITEM_POKE_BALL
	end

SafariZone_North_EventScript_ItemQuickClaw::
	finditem ITEM_POKE_BALL
	end

SeafoamIslands_1F_EventScript_ItemIceHeal::
	finditem ITEM_POKE_BALL
	end

SeafoamIslands_B1F_EventScript_ItemWaterStone::
	finditem ITEM_POKE_BALL
	end

SeafoamIslands_B1F_EventScript_ItemRevive::
	finditem ITEM_POKE_BALL
	end

SeafoamIslands_B2F_EventScript_ItemBigPearl::
	finditem ITEM_POKE_BALL
	end

SeafoamIslands_B4F_EventScript_ItemUltraBall::
	finditem ITEM_POKE_BALL
	end

FourIsland_EventScript_ItemStarPiece::
	finditem ITEM_POKE_BALL
	end

FourIsland_EventScript_ItemStardust::
	finditem ITEM_POKE_BALL
	end

OneIsland_KindleRoad_EventScript_ItemEther::
	finditem ITEM_POKE_BALL
	end

OneIsland_KindleRoad_EventScript_ItemMaxRepel::
	finditem ITEM_POKE_BALL
	end

OneIsland_KindleRoad_EventScript_ItemCarbos::
	finditem ITEM_POKE_BALL
	end

FiveIsland_Meadow_EventScript_ItemMaxPotion::
	finditem ITEM_POKE_BALL
	end

FiveIsland_Meadow_EventScript_ItemPPUp::
	finditem ITEM_POKE_BALL
	end

FiveIsland_MemorialPillar_EventScript_ItemMetalCoat::
	finditem ITEM_POKE_BALL
	end

SixIsland_OutcastIsland_EventScript_ItemPPUp::
	finditem ITEM_POKE_BALL
	end

SixIsland_WaterPath_EventScript_ItemElixir::
	finditem ITEM_POKE_BALL
	end

SixIsland_WaterPath_EventScript_ItemDragonScale::
	finditem ITEM_POKE_BALL
	end

SixIsland_RuinValley_EventScript_ItemFullRestore::
	finditem ITEM_POKE_BALL
	end

SixIsland_RuinValley_EventScript_ItemHPUp::
	finditem ITEM_POKE_BALL
	end

SixIsland_RuinValley_EventScript_ItemSunStone::
	finditem ITEM_POKE_BALL
	end

SevenIsland_SevaultCanyon_EventScript_ItemKingsRock::
	finditem ITEM_POKE_BALL
	end

SevenIsland_SevaultCanyon_EventScript_ItemMaxElixir::
	finditem ITEM_POKE_BALL
	end

SevenIsland_SevaultCanyon_EventScript_ItemNugget::
	finditem ITEM_POKE_BALL
	end

ThreeIsland_BerryForest_EventScript_ItemMaxEther::
	finditem ITEM_POKE_BALL
	end

ThreeIsland_BerryForest_EventScript_ItemFullHeal::
	finditem ITEM_POKE_BALL
	end

ThreeIsland_BerryForest_EventScript_ItemMaxElixir::
	finditem ITEM_POKE_BALL
	end

MtEmber_Exterior_EventScript_ItemUltraBall::
	finditem ITEM_POKE_BALL
	end

MtEmber_Exterior_EventScript_ItemFireStone::
	finditem ITEM_POKE_BALL
	end

MtEmber_Exterior_EventScript_ItemDireHit::
	finditem ITEM_POKE_BALL
	end

FourIsland_IcefallCave_1F_EventScript_ItemUltraBall::
	finditem ITEM_POKE_BALL
	end

FourIsland_IcefallCave_1F_EventScript_ItemHM07::
	finditem ITEM_HM07
	end

FourIsland_IcefallCave_B1F_EventScript_ItemFullRestore::
	finditem ITEM_POKE_BALL
	end

FourIsland_IcefallCave_B1F_EventScript_ItemNeverMeltIce::
	finditem ITEM_POKE_BALL
	end

FiveIsland_RocketWarehouse_EventScript_ItemBigPearl::
	finditem ITEM_POKE_BALL
	end

FiveIsland_RocketWarehouse_EventScript_ItemTM36::
	finditem ITEM_POKE_BALL
	end

FiveIsland_RocketWarehouse_EventScript_ItemPearl::
	finditem ITEM_POKE_BALL
	end

FiveIsland_RocketWarehouse_EventScript_ItemUpGrade::
	finditem ITEM_POKE_BALL
	end

FiveIsland_LostCave_Room10_EventScript_ItemSilkScarf::
	finditem ITEM_POKE_BALL
	end

FiveIsland_LostCave_Room11_EventScript_ItemLaxIncense::
	finditem ITEM_POKE_BALL
	end

FiveIsland_LostCave_Room12_EventScript_ItemSeaIncense::
	finditem ITEM_POKE_BALL
	end

FiveIsland_LostCave_Room13_EventScript_ItemMaxRevive::
	finditem ITEM_POKE_BALL
	end

FiveIsland_LostCave_Room14_EventScript_ItemRareCandy::
	finditem ITEM_POKE_BALL
	end

SevenIsland_SevaultCanyon_House_EventScript_ItemLuckyPunch::
	finditem ITEM_POKE_BALL
	end

SilphCo_4F_EventScript_ItemTM41::
	finditem ITEM_POKE_BALL
	end
